version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: ai-platform-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    networks:
      - ai-platform-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  createbuckets:
    image: minio/mc
    container_name: ai-platform-createbuckets
    depends_on:
      - minio
    networks:
      - ai-platform-network
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/models;
      /usr/bin/mc mb myminio/cache;
      /usr/bin/mc policy set download myminio/models;
      exit 0;
      "

networks:
  ai-platform-network:
    external: true

volumes:
  minio-data: