apiVersion: v1
kind: Secret
metadata:
  name: ai-platform-secrets
type: Opaque
stringData:
  database-url: "postgresql://aiuser:aipassword@postgres-service:5432/aiplatform"
  jwt-secret: "your_secure_jwt_secret_replace_this_in_production"
  postgres-user: "aiuser"
  postgres-password: "aipassword"